export const Villes = {
    'Ariana' : [
        'Borj Louzir',
        'Chotrana',
        'Ennasr',
        'Ettadhamen',
        'Ghazela',
        'Jardins Del Menzah',
        'La Soukra',
        'Mnihla',
        'Raoued',
        'Sidi Thabet',
    ],
    'Ben Arous' : [
        'Boumhel',
        'El Mourouj',
        'Ezzahra',
        'Fouchana',
        'Hamem Chott',
        'Hammem Lif',
        'Medina Jedida',
        'Mouhamedia',
        'Morneg',
        'Mégrine',
        'Radés'
    ],
    'Béja' : [
        'Amdoun',
        'Béja Nord',
        'Béja Sud',
        'El Ksar',
        'Goubellat',
        'Medjez el-Bab',
        'Nefza',
        'Testour',
        'Thibar',
        'Tébousouk'
    ],
    'Bizerte' : [
        'Bizerte Nord',
        'Bizerte Sud',
        'Djoumime',
        'Ghar El Melh',
        'Ghezala',
        'Mateur',
        'Menzel Bourguiba',
        'Ras Jebel',
        'Sejenane',
        'Tinja',
        'Utique',
        'Zarzouna'
    ],
    'Gabés' : [
        'El Hamma',
        'Gabés Médina',
        'Gabés Ouest',
        'Gabés Sud',
        'Ghanouch',
        'Mareth',
        'Matmata',
        'Métouia',
        'Nouvelle Matmata'
    ],
    'Gafsa' : [
        'Belkhir',
        'El Guettar',
        'Gafsa Nord',
        'Gafsa Sud',
        'Mdhila',
        'Métlaoui',
        'Oum El Araies',
        'Redeyef',
        'Sened',
        'Sidi Aich'
    ],
    'Jendouba' : [
        'Ain Draham',
        'Balta-Bou Aouane',
        'Bou Salem',
        'Fernena',
        'Ghardimaou',
        'Jendouba Nord',
        'Oued Meliz',
        'Tabarka'
    ],
    'Kairouan' : [
        'Bouhajla',
        'Chebika',
        'Echrarda',
        'El Alaa',
        'El Ouslatia',
        'Haffouz',
        'Hajeb El Ayoun',
        'Kairouan Nord',
        'Kairouan Sud',
        'Nesrallah',
        'Sbikha'
    ],
    'Kasserine' : [
        'Djedaliane',
        'Ezzouhour',
        'El Ayoun',
        'Foussana',
        'Fériana',
        'Hassi Ferid',
        'Hidra',
        'Kasserine Nord',
        'Kasserine Sud',
        'Majel Bel Abbés',
        'Sbeitla',
        'Sbiba',
        'Thala'
    ],
    'Kébili' : [
        'Douz Nord',
        'Douz Sud',
        'Faouar',
        'Kébili Nord',
        'Kébili Sud',
        'Souk Lahad'
    ],
    'La manouba' : [
        'Borj El Amri',
        'Denden',
        'Djedeida',
        'Douar Hicher',
        'El Battan',
        'Manouba Ville',
        'Menzel El Habib',
        'Mournaguia',
        'Oued Elil',
        'Tebourba'
    ],
    'Le Kef' : [
        'Dahmani',
        'Djerissa',
        'El Ksour',
        'Es-Sers',
        'Kalaat Khasbah',
        'Kalaat Snan',
        'Kef Est',
        'Kef Ouest',
        'Nebeur',
        'Sekiet Sidi Youssef',
        'Tajerouine'
    ],
    'Mahdia' : [
        'Bou Merdés',
        'Chebba',
        'Chorbane',
        'El Jem',
        'Essoussi',
        'Hebira',
        'Ksour Essef',
        'Mellouléche',
        'Ouled Chemekh',
        'Sidi Alouane'
    ],
    'Monastir' : [
        'Belkalta',
        'Bembla',
        'Beni Hassen',
        'Jemmal',
        'Ksar Hellal',
        'Ksibet el-Médiouni',
        'Moknine',
        'Ouerdanine',
        'Sahline',
        'Sayada-Lamta-Bou Hajar',
        'Téboulba',
        'Zéramdine'
    ],
    'Médenine' : [
        'Ben Gardane',
        'Beni Khadech',
        'Djerba -Ajim',
        'Djerba -Midoun',
        'Djerba -Houmet Souk',
        'Médenine Nord',
        'Médenine Sud',
        'Sidi Makhlouf',
        'Zarzis'
    ],
    'Nabeul' : [
        'Bou Argoub',
        'Béni Khalled',
        'Béni Khiar',
        'Dar Chaabane El Fehri',
        'El Haouaria',
        'El Mida',
        'Grombalia',
        'Hammam Ghezéze',
        'Hammamet',
        'Hammamet Centre',
        'Hammamet Sud',
        'Korba',
        'Kélibia',
        'Menzel Bouzelfa',
        'Menzel Temime',
        'Mrezga',
        'Soliman',
        'Takelsa',
    ],
    'Sfax' : [
        'Agareb',
        'Bir Ali Ben Khalifa',
        'El Amra',
        'El Hencha',
        'Ghraiba',
        'Jebiniana',
        'Kerkennah',
        'Mahrés',
        'Menzel Chaker',
        'Route Mehdia',
        'Route Menzel Chaker',
        'Route Sokra',
        'Route Tunis',
        'Route el Afrane',
        'Route el Ain',
        'Sakiet Eddaier',
        'Sakiet Ezzit',
        'Sfax Médina',
        'Sfax Ville',
        'Skhira',
        'Thyna'
    ],
    'Sidi bouzid' : [
        'Bir El Hafey',
        'Cebbala Ouled Asker',
        'Jilma',
        'Meknassy',
        'Menzel Bouzaiane',
        'Mezzouna',
        'Ouled Haffouz',
        'Regueb',
        'Sidi Ali Ben Aoun',
        'Sidi Bouzid Est',
        'Siddi Bouzid Ouest',
        'Souk Jedid'
    ],
    'Siliana' : [
        'Bargou',
        'Bou Arada',
        'El Aroussa',
        'El Krib',
        'Gaafour',
        'Kesra',
        'Makthar',
        'Rouhia',
        'Sidi Bou Rouis',
        'Siliana Nord',
        'Siliana Sud',
    ],
    'Sousse' : [
        'Akouda',
        'Boudicha',
        'Enfidha',
        'Hamem Soussa',
        'Hergla',
        'Kalaa Kebira',
        'Kalaa Sghira',
        'Kantaoui',
        'Kondar',
        "M'saken",
        'Sahloul',
        'Sidi Bou Ali',
        'Sidi El Héni',
        'Sousse Jawhara',
        'Sousse Médina',
        "Sousse Riadh",
        'Sousse Sidi Abdelhamid',
        'Zaouit-Ksibat Thrayett'
    ],
    'Tataouine' : [
        'Bir Lahmar',
        'Dehiba',
        'Ghomrassen',
        'Remada',
        'Smar',
        'Tataouine Nord',
        'Tataouine Sud'
    ],
    'Touzeur' : [
        'Degache',
        'Hazoua',
        'Nefta',
        'Tameghza'
    ],
    'Tunis' : [
        'Agba',
        'Carthage',
        'Centre Urbain Nord',
        'Centre Ville -Lafayette',
        'Cité El Khadra',
        'Cité Olympique',
        'Djebel Jelloud',
        'El Kabaria',
        'El Omrane',
        'El Omrane Supérieur',
        'El Ouardia',
        'Ettahrir',
        'Ezzouhour',
        'Hraira',
        "L'aouina",
        'La Goulette',
        'La Marsa',
        'Le Bardo',
        'Le Kram',
        'Manar',
        'Menzah',
        'Menzel Jemil',
        'Mutuelleville',
        'Médina',
        'Sidi Bou Said',
        'Sidi Daoud',
        'Sidi El Béchir',
        'Sidi Hassine',
        'Séjoumi'
    ],
    'Zaghouan' : [
        'Bir Mchergua',
        'El Fahs',
        'En-Nadhour',
        'Ez-Zeriba',
        'Saouaf',
    ]
    
}